sonar.projectKey=3tier-application
sonar.projectName=3Tier Application
sonar.organization=app-finops-hv
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.github/**,**/__pycache__/**,**/*.pyc,**/*.md
sonar.inclusions=backend/**,frontend/**,database/**,vulnerableapp.js,vulnerableapp.py
sonar.sourceEncoding=UTF-8
sonar.python.version=3
sonar.javascript.file.suffixes=.js,.jsx
